blog/urls.py
from django.urls import path
from . import views
# from .views import 

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('category/<str:slug>/', views.PostByCategory.as_view(), name='post_by_category'),
    path('tags/<slug:slug>/', views.PostByTag.as_view(), name='post_by_tag'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),
] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from  django.utils import timezone
from django.contrib.auth.models import User 
from taggit.managers import TaggableManager
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    tag = TaggableManager()
    image = models.ImageField(upload_to='posts/')
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    description = models.TextField(max_length=15000)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='post_category')
    slug = models.SlugField(null=True, blank=True)

    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category
from taggit.models import Tag
from django.db.models import Count
from django.db.models.query_utils import Q
# Create your views here.

class PostList(ListView):
    model = Post
    paginate_by = 1
    
    def get_queryset(self):
        name = self.request.GET.get('q','')
        object_list = Post.objects.filter(
            Q(title__icontains=name)|
            Q(description__icontains=name)
            
            )
        return object_list
    
    
class PostDetail(DetailView):
    model = Post
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))
        context["tags"] = Tag.objects.all()
        context["recent_posts"] = Post.objects.all()[:3]
        return context
    
class PostByCategory(ListView):
    model = Post
    
    
    def get_queryset(self):
        object_list = Post.objects.filter(
            Q(category__name__icontains=self.kwargs['slug']))
            
        return object_list
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))
    #     context["tags"] = Tag.objects.all()
    #     context["recent_posts"] = Post.objects.all()[:3]
    #     return context

class PostByTag(ListView):
    model = Post
    
    def get_queryset(self):
        tag_slug = self.kwargs['slug']
        return Post.objects.filter(tag__slug=tag_slug)
    
    # def get_queryset(self):
    #     return Post.objects.filter(tag__name=self.kwargs['tag'])
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))
    #     context["tags"] = Tag.objects.all()
    #     context["recent_posts"] = Post.objects.all()[:3]
    #     return context

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static%}

{% block body %}


<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a
                            href="blog.html">Blog</a></span> <span>Blog Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp;
                    Articles</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ftco-animate">
                <h2 class="mb-3">{{post}}</h2>
                <p>{{post.description|safe}}</p>

                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">

                        {% for tag in post.tag.all %}

                        <a href="#" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}


                    </div>
                </div>

                <div class="about-author d-flex p-5 bg-light">
                    <div class="bio align-self-md-center mr-5">
                        <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc align-self-md-center">
                        <h3>Lance Smith</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">6 Comments</h3>
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">June 27, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">June 27, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>

                            <ul class="children">
                                <li class="comment">
                                    <div class="vcard bio">
                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <h3>John Doe</h3>
                                        <div class="meta">June 27, 2018 at 2:21pm</div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem
                                            laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe
                                            enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?
                                        </p>
                                        <p><a href="#" class="reply">Reply</a></p>
                                    </div>


                                    <ul class="children">
                                        <li class="comment">
                                            <div class="vcard bio">
                                                <img src="images/person_1.jpg" alt="Image placeholder">
                                            </div>
                                            <div class="comment-body">
                                                <h3>John Doe</h3>
                                                <div class="meta">June 27, 2018 at 2:21pm</div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur
                                                    quidem laborum necessitatibus, ipsam impedit vitae autem, eum
                                                    officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum
                                                    impedit necessitatibus, nihil?</p>
                                                <p><a href="#" class="reply">Reply</a></p>
                                            </div>

                                            <ul class="children">
                                                <li class="comment">
                                                    <div class="vcard bio">
                                                        <img src="images/person_1.jpg" alt="Image placeholder">
                                                    </div>
                                                    <div class="comment-body">
                                                        <h3>John Doe</h3>
                                                        <div class="meta">June 27, 2018 at 2:21pm</div>
                                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                                            Pariatur quidem laborum necessitatibus, ipsam impedit vitae
                                                            autem, eum officia, fugiat saepe enim sapiente iste iure!
                                                            Quam voluptas earum impedit necessitatibus, nihil?</p>
                                                        <p><a href="#" class="reply">Reply</a></p>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="images/person_1.jpg" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">June 27, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" class="p-5 bg-light">
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-md-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form action="{% url 'blog:post_list' %}" method="get" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        {% for category in categories %}
                            <li><a href="{% url 'blog:post_by_category' category %}">{{category}} <span>({{category.post_count}})</span></a></li>
                        {% endfor %}
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>

                    {% for post in recent_posts %}
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4" href="{{post.get_absolute_url}}" style="background-image: url({{post.image.url}});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="{{post.get_absolute_url}}">{{post}}</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> {{post.created_at|date:'F j Y'}}</a></div>
                                    <div><a href="#"><span class="icon-person"></span> {{post.author}}</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}



                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="{% url 'blog:post_by_tag' tag.slug %}" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>


            </div>

        </div>
    </div>
</section> <!-- .section -->

{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static%}

{% block body %}
        <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp; Articles</h1>
          </div>
        </div>
      </div>
    </div>


    <section class="ftco-section bg-light">
      <div class="container">
        <div class="row d-flex">
            
            {% for post in post_list %}
                    <div class="col-md-3 d-flex ftco-animate">
                        <div class="blog-entry align-self-stretch">
                            <a href="{{post.get_absolute_url}}" class="block-20"
                                style="background-image: url({{post.image.url}});"></a>
                            <div class="text p-4 d-block">
                                <span class="tag">Tips, Travel</span>
                                <h3 class="heading mt-3"><a href="{{post.get_absolute_url}}">{{post}}</a></h3>
                                <div class="meta mb-3">
                                    <div><a href="#">{{post.created_at|date:'F j Y'}}</a></div>
                                    <div><a href="#">{{post.author}}</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
                
          
          
        </div>
        {% if is_paginated %}
                
                    <div class="row mt-5">
                        <div class="col text-center">
                            <div class="block-27">
                                <ul>
                                    
                                    {% if  page_obj.has_previous %}
                                        <li><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&lt;</span></li>
                                    {% endif %}
                                    
                                    {% for i in paginator.page_range %}
                                        
                                        {% if page_obj.number == i %}
                                            <li class="active"><span>{{i}}</span></li>
                                        {% else %}
                                            <li><a href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}
                                            
                                    {% endfor %}
                                        
                                    {% if  page_obj.has_next %}
                                        <li><a href="?page={{page_obj.next_page_number}}">&gt;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&gt;</span></li>
                                    {% endif %}
                                
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
      </div>
    </section>

{% endblock body %}
    